const characters = "aABbDEfdeghiHWOVZowrzFyqQR1234567890";
const charactersLength = characters.length;

function generateId(length) {
    let generatedID = "";
    for(let i = 0; i < length; i++) {
        generatedID += characters[parseInt(Math.floor(Math.random() * charactersLength - 1))];
    }
    return generatedID;
}

export default [
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'movie',
        title: 'Thor: Love and Thunder',
        IMDb: '6.4/10',
        rating: 'PG-13',
        genres: ['Action', 'Comedy'],
        country: 'United States',
        releaseDate: 'July 9 2018',
        tomato: '64%',
        audienceScore: '77%',
        runtime: '2h 5m',
        language: 'English',
        poster: './logo192.png',
    },
    {
        id: generateId(7),
        type: 'series',
        title: 'Elite',
        poster: './wall.jpg',
        genres: ['Action', 'Comedy'], // genre of Season 1
        series: [
            {
                id: generateId(7),
                title: 'Elite Season 1',
                MDb: '6.4/10',
                rating: 'PG-13',
                genres: ['Action', 'Comedy'],
                country: 'United States',
                releaseDate: 'July 9 2018',
                tomato: '64%',
                audienceScore: '77%',
                runtime: '2h 5m',
                language: 'English',
                poster: './logo192.png',
            },
            {
                id: generateId(7),
                title: 'Elite Season 2',
                MDb: '6.4/10',
                rating: 'PG-13',
                genres: ['Action', 'Comedy'],
                country: 'United States',
                releaseDate: 'July 9 2018',
                tomato: '64%',
                audienceScore: '77%',
                runtime: '2h 5m',
                language: 'English',
                poster: './logo192.png',
            }
        ]
    },
    {
        id: generateId(7),
        type: 'series',
        title: 'Elite',
        poster: './logo192.png',
        genres: ['Action', 'Comedy'], // genre of Season 1
        series: [
            {
                id: generateId(7),
                title: 'Elite Season 1',
                MDb: '6.4/10',
                rating: 'PG-13',
                genres: ['Action', 'Comedy'],
                country: 'United States',
                releaseDate: 'July 9 2018',
                tomato: '64%',
                audienceScore: '77%',
                runtime: '2h 5m',
                language: 'English',
                poster: './logo192.png',
            },
            {
                id: generateId(7),
                title: 'Elite Season 2',
                MDb: '6.4/10',
                rating: 'PG-13',
                genres: ['Action', 'Comedy'],
                country: 'United States',
                releaseDate: 'July 9 2018',
                tomato: '64%',
                audienceScore: '77%',
                runtime: '2h 5m',
                language: 'English',
                poster: './logo192.png',
            }
        ]
    },
    {
        id: generateId(7),
        type: 'series',
        title: 'Elite',
        poster: './sha.jpg',
        genres: ['Action', 'Comedy'], // genre of Season 1
        series: [
            {
                id: generateId(7),
                title: 'Elite Season 1',
                MDb: '6.4/10',
                rating: 'PG-13',
                genres: ['Action', 'Comedy'],
                country: 'United States',
                releaseDate: 'July 9 2018',
                tomato: '64%',
                audienceScore: '77%',
                runtime: '2h 5m',
                language: 'English',
                poster: './logo192.png',
            },
            {
                id: generateId(7),
                title: 'Elite Season 2',
                MDb: '6.4/10',
                rating: 'PG-13',
                genres: ['Action', 'Comedy'],
                country: 'United States',
                releaseDate: 'July 9 2018',
                tomato: '64%',
                audienceScore: '77%',
                runtime: '2h 5m',
                language: 'English',
                poster: './sha.jpg',
            }
        ]
    },
    {
        id: generateId(7),
        type: 'series',
        title: 'Elite',
        poster: './logo192.png',
        genres: ['Action', 'Comedy'], // genre of Season 1
        series: [
            {
                id: generateId(7),
                title: 'Elite Season 1',
                MDb: '6.4/10',
                rating: 'PG-13',
                genres: ['Action', 'Comedy'],
                country: 'United States',
                releaseDate: 'July 9 2018',
                tomato: '64%',
                audienceScore: '77%',
                runtime: '2h 5m',
                language: 'English',
                poster: './logo192.png',
            },
            {
                id: generateId(7),
                title: 'Elite Season 2',
                MDb: '6.4/10',
                rating: 'PG-13',
                genres: ['Action', 'Comedy'],
                country: 'United States',
                releaseDate: 'July 9 2018',
                tomato: '64%',
                audienceScore: '77%',
                runtime: '2h 5m',
                language: 'English',
                poster: './logo192.png',
            }
        ]
    },
    {
        id: generateId(7),
        type: 'series',
        title: 'Elite',
        poster: './logo192.png',
        genres: ['Action', 'Comedy'], // genre of Season 1
        series: [
            {
                id: generateId(7),
                title: 'Elite Season 1',
                MDb: '6.4/10',
                rating: 'PG-13',
                genres: ['Action', 'Comedy'],
                country: 'United States',
                releaseDate: 'July 9 2018',
                tomato: '64%',
                audienceScore: '77%',
                runtime: '2h 5m',
                language: 'English',
                poster: './logo192.png',
            },
            {
                id: generateId(7),
                title: 'Elite Season 2',
                MDb: '6.4/10',
                rating: 'PG-13',
                genres: ['Action', 'Comedy'],
                country: 'United States',
                releaseDate: 'July 9 2018',
                tomato: '64%',
                audienceScore: '77%',
                runtime: '2h 5m',
                language: 'English',
                poster: './logo192.png',
            }
        ]
    }
];